env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode9.3
      before_install:
        - ./scripts/install_swiftlint.sh
      script:
        - swiftlint
        - set -o pipefail
        - xcodebuild build-for-testing test-without-building -scheme Alembic -configuration Release ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build-for-testing test-without-building -scheme Alembic -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' ENABLE_TESTABILITY=YES | xcpretty - c
        - xcodebuild build-for-testing test-without-building -scheme Alembic -configuration Release -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV' ENABLE_TESTABILITY=YES | xcpretty -c
        - xcodebuild build -scheme Alembic -configuration Release -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch - 38mm' ENABLE_TESTABILITY=YES | xcpretty -c

    - os: osx
      language: generic
      osx_image: xcode9.3
      script:
        - swift build
        - swift test

    - os: linux
      language: generic
      dist: trusty
      sudo: required
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - ./scripts/test_linux.sh

notifications:
  email: false
